# Generated by Django 6.0.6 on 2026-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
